### ISSUE TITLE
Costruire applicazioni modulari con ReactJS e Redux

### ISSUE THREAD

**Issue by gianmarcotoso** [TorinoJS/torinojs.github.io#17]
Se interessa posso riproporre il talk che farò a inizio ottobre al ReactJS day di Verona, "Building Modular Redux Application", ma in italiano anziché in inglese. Se piace a Verona ovviamente, se invece mi tirano addosso pomodori e lattughe posso fare un'intro a ReactJS :)

**Comment by eclipse1985** [comment]
+1

**Comment by grigio** [comment]
Ciao @gianmarcotoso, mi spiace ora siamo solo più in fase di votazione. https://github.com/TorinoJS/torinojs.github.io/issues/11

Se segui https://gitter.im/TorinoJS/chat puoi rimanere informato sulle #jsNight future.
