### ISSUE TITLE
Webinar SOAJS

### ISSUE THREAD

**Issue by carlok** [TorinoJS/torinojs.github.io#4]
Webinar (Hangout + Youtube) su SOAJS tenuto dal team di sviluppo di Boston per TorinoJS.
:)
Si potrebbe estendere anche agli interessati di JS in Italia in generale.
Data: 21 aprile.
Orario: 18:30
Hangout: https://plus.google.com/u/0/events/cli3vldp3lrdt65n7oj9ogtpa00

**Comment by grigio** [comment]
@carlok ci ha confermato che il **giovedì 21 aprile alle 18.30** il team di [SOAJS](https://github.com/soajs/soajs) è disponibile per un webinar gratuito dedicato a TorinoJS sul framework JavaScript/NodeJS che stanno sviluppando.

Se siete interessati all'iniziativa cliccate su "subscribe" così rimarrete aggiornati su tutti i dettagli
![schermata 2016-04-04 alle 12 52 07](https://cloud.githubusercontent.com/assets/8074/14246496/d1bffe80-fa67-11e5-9670-e265cacd6c4f.png)
(che trovate alla vs destra)

**Comment by grigio** [comment]
Grazie @carlok per aver aggiunto il link di Hangout.

PS: Se non avete mai utilizzato Hangout provatelo prima.. potrebbero essere necessari plugin :)
