### ISSUE TITLE
+Web Applications su sistemi embedded

### ISSUE THREAD

**Issue by gmacario** [TorinoJS/torinojs.github.io#6]
Vorrei raccontarvi qualche esperienza nel deployment di applicazioni web su sistemi embedded - con particolare riferimento a quelli basati su [UDOO NEO](http://www.udoo.org/udoo-neo/)

**Comment by antonellopasella** [comment]
+1

**Comment by antonellopasella** [comment]
Bello! +1

**Comment by gmacario** [comment]
The slides of my tonight speech at @torinojs are available at https://t.co/g7cu5kF3Cz
