### ISSUE TITLE
+Sistemi LoRa

### ISSUE THREAD

**Issue by Muwattalli** [TorinoJS/torinojs.github.io#8]
Io (Gianfranco PONCINI (Muwattalli)) e Gianpaolo Macario stiamo preparando uno shield per Arduino e UDOO Neo, per tentare di mettere in piedi la prima rete Lora a Torino, eventualmente complementare alla rete Ninux, che su lunghe distanze qui in citta' ha grossi problemi di propagazione. Se interessa ..

**Comment by dolcestilnuovo65** [comment]
Ciao, propongo un talk su Typesctipt
in linea di massima i punti
1) Perchè usare la progettazione OO? fare una new di un oggetto non vuol dire usare l'OO nella sua potenza. 
2) Piccola review dell'OO
   a) ereditarietà
   b) polimorfismo
   c) incapsulamento
3) Typescipt ovvero Javascript  + OO
4) Tutto ciò che Javascript è anche Typescipt (Jquery,Angualrjs,BackboneJs,etc)
5) Typescript vs Coffescript, ECMA6 e DART
6) Moduli e librerie
7) Ide e Debugger
8) Conclusioni

**Comment by gmacario** [comment]
+1

**Comment by antonellopasella** [comment]
Sarebbe utile dettagliare meglio la relazione del progetto con JavaScript

**Comment by grigio** [comment]
@Muwattalli  ciao potresti mettere le slide online? es. slideshare/speakerdeck tnx

**Comment by gmacario** [comment]
See https://github.com/Muwattalli/LoRaShield/raw/master/Presentazione_LoRa.pdf

**Comment by grigio** [comment]
Grazie

**Comment by neskov7** [comment]
http://www.slideshare.net/paolomarino5/typescript1

**Comment by dolcestilnuovo65** [comment]
http://www.slideshare.net/paolomarino5/typescript1

**Comment by gmacario** [comment]
@dolcestilnuovo65 : Thanks,  I copied the link above to your https://github.com/TorinoJS/torinojs.github.io/issues/9
