### ISSUE TITLE
+Typescript= JavaScript  + OO

### ISSUE THREAD

**Issue by dolcestilnuovo65** [TorinoJS/torinojs.github.io#9]
Ciao, propongo un talk su Typesctipt
in linea di massima i punti
1) Perchè usare la progettazione OO? fare una new di un oggetto non vuol dire usare l'OO nella sua potenza. 
2) Piccola review dell'OO
a) ereditarietà
b) polimorfismo
c) incapsulamento
3) Typescipt ovvero Javascript + OO OPENSOURCE
4) Tutto ciò che Javascript è anche Typescipt (Jquery,Angualrjs,BackboneJs,etc)
5) Typescript vs Coffescript, ECMA6 e DART
6) Moduli e librerie
7) Ide e Debugger
8) Conclusioni

**Comment by kenta88** [comment]
+1

**Comment by gmacario** [comment]
+1

**Comment by grigio** [comment]
+1 Ci sono tanti argomenti, il mio consiglio è di concentrarsi più su gli argomenti distintivi di Typescript rispetto JavaScript ES6, visto che comunque eriditarietà, classi,.. ora ci sono anche in JavaScript

**Comment by dolcestilnuovo65** [comment]
Giusta osservazione, penso a questo punto di fare  tutto insieme e quindi
di vedere l'OO attraverso typescipt.

2016-05-09 10:40 GMT+02:00 Luigi Maselli notifications@github.com:

**Comment by dolcestilnuovo65** [comment]
Teniamo conto che per molti programmatori web programmare OO significa fare
una new di un oggetto quindi non diamo niente di scontato.
Stesso dicasi con ECMA6: inutile utilizzarlo se non si ha capito in
profondità i vantaggi della metodologia OO

Il giorno 9 maggio 2016 11:00, Paolo Marino pmariner65@gmail.com ha
scritto:

**Comment by dolcestilnuovo65** [comment]
Quindi io farei un'introduzione al perchè dell'OO, un'introduzione a
Typescrit e poi farei vedere come Typescript permette (al 90%) di scrivere
codice con la metodologia OO, che ne dite?

Il giorno 9 maggio 2016 11:02, Paolo Marino pmariner65@gmail.com ha
scritto:

**Comment by dolcestilnuovo65** [comment]
Ah io lo farei con Visual Studio, spero che la cosa non crei crisi di
rigetto

Il giorno 9 maggio 2016 11:05, Paolo Marino pmariner65@gmail.com ha
scritto:

**Comment by grigio** [comment]
@dolcestilnuovo65 i miei erano solo suggerimenti, poi sei libero i organizzarti come vuoi. Tieni conto che il tempo è di 25min e non c'é la pretesa di sviscerare tutto il possibile immaginabile. Puoi anche candidarti la prossima volta per approfondire altriargomenti.

Come editor puoi usare quello che preferisci. Se usi Visual Studio Code potrebbe essere un po' più carino visto che è multipiattaforma e open source.

**Comment by antonellopasella** [comment]
+1 (anche se non adoro TypeScript) 😀

**Comment by dolcestilnuovo65** [comment]
certo, si parlerà anche di quello...

2016-05-09 23:14 GMT+02:00 Antonello Pasella notifications@github.com:

**Comment by grigio** [comment]
@dolcestilnuovo65 ciao potresti mettere le slide online? es. slideshare/speakerdeck tnx

**Comment by gmacario** [comment]
@dolcestilnuovo65 slides available at http://www.slideshare.net/paolomarino5/typescript1
